// Type definition that helps manage metadata
import type { Metadata } from 'next'
 
// Defines some metadata, e.g. sets title
export const metadata: Metadata = {
  title: 'William & Mary Syllabus Repository',
}
 
// Creates functional component Page
export default function Page() {
  return (
    <div>
      <>
        <title>William & Mary Syllabus Repository</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/favicon.ico" />
      </>
      <main className='bg-white px-10'>
        <section>
          <nav className='flex justify-between'>
            <h1>Syllabuses for the College of William & Mary</h1>
          </nav>
        </section>
      </main>
    </div>
  );
}