import type { Metadata } from 'next'
import Syllabus from './Syllabus';

export const metadata: Metadata = {
  title: 'William & Mary Syllabus Repository',
}
 

export default function Page() {
  return (
    <div>
      <>
        <title>William & Mary Syllabus Repository</title>
        <meta name="description" content="Generated by create-next-app" />
        <link rel="icon" href="/favicon.ico" />
      </>
      <main className='bg-white px-10'>
        <h1 className='text-5xl text-center'>William & Mary Syllabus Repository</h1>
        <div>
          <ul>
            <li>
              <Syllabus link='./syllabuses/CSCI_243_Spring_2025_Davis.pdf'/>
            </li>
          </ul>
        </div>
      </main>
    </div>
  );
}